language: cpp
compiler:
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libc6-i386
  - wget http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.sh
  - sudo sh cmake-3.2.3-Linux-x86_64.sh --exclude-subdir --prefix=/usr/local
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install libstdc++-4.8-dev
script: git clone https://github.com/llvm-mirror/llvm.git --depth 1 && cd llvm/tools && git clone https://github.com/llvm-mirror/clang.git --depth 1 && cd clang/tools && git clone https://github.com/rettichschnidi/clang-misracpp2008.git --depth 1 && echo 'add_subdirectory(clang-misracpp2008)' >> CMakeLists.txt && cd ../../../ && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release ../ && make -j10 check-misracpp2008
