env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Eo1br0u89lVVa9Rat+sv8fP/wN6fdMpftI9+eYhQzC0nkM0bwWozg6V2Y1cuLMi96SDK2qw+CnnfdxpsZvHVfi2N2Bz45l++oGUvDX//1IKHkA5yuSNyMJqKPXXFntjW1cA29HVUIByLu4NFQ9TeeQFUQ8thiboFJJ/r01y1c6U="

addons:
  coverity_scan:
    project:
      name: "rettichschnidi/clang-misracpp2008"
      description: "An open source checker for MISRA C++:2008 rules. Implemented as LLVM/Clang plugin."
    notification_email: code@reto-schneider.ch
    build_command_prepend: "sudo apt-get update -qq && sudo apt-get install libc6-i386 && wget http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.sh && sudo sh cmake-3.2.3-Linux-x86_64.sh --exclude-subdir --prefix=/usr/local && sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get -qq update && sudo apt-get -qq install libstdc++-4.8-dev && cd && git clone https://github.com/llvm-mirror/llvm.git --depth 1 && cd llvm/tools && git clone https://github.com/llvm-mirror/clang.git --depth 1 && cd clang/tools && git clone https://github.com/rettichschnidi/clang-misracpp2008.git --depth 1 && echo 'add_subdirectory(clang-misracpp2008)' >> CMakeLists.txt && cd ../../../ && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release ../"
    build_command: "cd build && make -j10 misracpp2008"
    branch_pattern: coverity_scan
script: echo "Nothing to do on the coverity_scan branch."
language: cpp
compiler:
  - clang
